### ISSUE TITLE
Identify UBports recovery via adb

### ISSUE THREAD

**Issue by Flohack74** [ubports/halium_bootable_recovery#22]
For proper installation having the UBports recovery onboard is mandatory. Currently the installer happily uses TWRP et.al. and tries to install UT with them, which fails.

Make recovery somehow identifyable from the outside via adb so that we can stop the installer from doing bad things.

**Comment by amartinz** [comment]
We can achieve this with setting a property inside the recovery init.rc.

Which name should the property have?

**Comment by amartinz** [comment]
Opened a PR with property ` ro.ubuntu.recovery`.
Feel free to adjust to your liking :)

Later on we need to pick it to other branches as well.

Also needs to be actually checked in installer, which is another TODO.

Example usage: `adb shell getprop ro.ubuntu.recovery`

it returns:
- `true`, if the recovery is UBports based
- nothing or any other value, if the recovery does not support installing Ubuntu Touch via `system-image-upgrader`

**Comment by amartinz** [comment]
updated property to `ro.ubuntu.recovery` based on feedback from @Flohack74

**Comment by amartinz** [comment]
This is possible now on the installer side with https://github.com/ubports/ubports-installer/pull/2529 and needs installer config changes done by the maintainers.

As all the patches have landed for the recoveries, they need to be rebuilt and it should start working.
